stages:
  - .pre
  - build
  - test
  - deploy
  - .post

Pre-Build-Environment:
  stage: .pre
  image: arlenlt/android-cross-compiler:latest
  tags:
    - docker
  script:
    - echo $PATH
    - echo $PYENV_ROOT
    - echo $ANDROID_NDK
    - cmake --version

build_armv7:
  stage: build
  image: arlenlt/android-cross-compiler:latest
  tags:
    - docker
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cmake --preset armv7 -DENABLE_SLOG=TRUE
    - pushd armv7/build
    - cmake --build .
    - cmake --install .
    - popd
  artifacts:
    paths:
    - ./armv7/install

build_win64:
  stage: build
  tags:
    - windows
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_UPDATE_FLAGS: --remote
  script:
    - cmake --preset win64 -DENABLE_SLOG=TRUE
    - pushd win64/build
    - cmake --build .
    - cmake --install .
    - popd
  artifacts:
    paths:
    - ./win64/install
